version: '4.13'

volumes:
  ollama:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama_files:/root/.ollama
    ports:
      - "11434:11434" 